### ISSUE TITLE
java launch failed

### ISSUE THREAD

**Issue by jollychang** [IG-Group/swagger-search#2]
```
[jollychang@William-15MBP]$ java --version
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

[jollychang@William-15MBP]$ java -jar ~/Downloads/swagger-search-0.5.2-standalone.jar -vvvvv
18:41:22,855 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:41:22,855 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
18:41:22,855 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/jollychang/Downloads/swagger-search-0.5.2-standalone.jar!/logback.xml]
18:41:22,866 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@4687fee7 - URL [jar:file:/Users/jollychang/Downloads/swagger-search-0.5.2-standalone.jar!/logback.xml] is not of type file
18:41:22,948 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
18:41:22,954 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [jar:file:/Users/jollychang/Downloads/swagger-search-0.5.2-standalone.jar!/logback.xml]
18:41:22,954 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
18:41:22,956 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:41:22,958 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
18:41:22,980 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
18:41:22,980 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
18:41:22,980 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
18:41:22,981 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
18:41:22,981 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
18:41:22,981 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
18:41:22,982 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4a0fc665 - Registering current configuration as safe fallback point

2018-08-21 18:41:23 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @4786ms
Exception in thread "main" java.lang.ExceptionInInitializerError
	at dynapath.defaults__init.load(Unknown Source)
	at dynapath.defaults__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at dynapath.util$loading__5569__auto____10075.invoke(util.clj:1)
	at dynapath.util__init.load(Unknown Source)
	at dynapath.util__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at com.ig.swagger.search.standalone$loading__5569__auto____36.invoke(standalone.clj:1)
	at com.ig.swagger.search.standalone__init.load(Unknown Source)
	at com.ig.swagger.search.standalone__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.RT.loadClassForName(RT.java:2196)
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.Util.loadWithClass(Util.java:250)
	at com.ig.swagger.search.standalone.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: sun.misc.Launcher$ExtClassLoader
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at dynapath.defaults$fn__10146.<clinit>(defaults.clj:14)
	... 72 more
```

**Comment by dlebrero** [comment]
Java 10 is not supported yet. Can you please try with Java 8 or with the Docker container?

**Comment by jollychang** [comment]
**Java 8**

```
[jollychang@William-15MBP]$ /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/bin/java -jar ~/Downloads/swagger-search-0.5.2-standalone.jar
19:49:08,820 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
19:49:08,820 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
19:49:08,820 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/jollychang/Downloads/swagger-search-0.5.2-standalone.jar!/logback.xml]
19:49:08,834 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@31dbf5bb - URL [jar:file:/Users/jollychang/Downloads/swagger-search-0.5.2-standalone.jar!/logback.xml] is not of type file
19:49:08,913 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
19:49:08,923 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [jar:file:/Users/jollychang/Downloads/swagger-search-0.5.2-standalone.jar!/logback.xml]
19:49:08,923 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
19:49:08,925 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
19:49:08,928 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
19:49:08,953 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
19:49:08,953 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
19:49:08,953 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
19:49:08,954 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
19:49:08,954 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
19:49:08,954 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
19:49:08,955 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1f19d423 - Registering current configuration as safe fallback point

2018-08-21 19:49:09 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @4888ms
2018-08-21 19:49:09 [main] INFO  com.ig.swagger.search.standalone - Adding /Users/jollychang/Works/zhspecs/swagger_files to classpath
Exception in thread "main" java.lang.RuntimeException: No swagger.config.edn file at $SWAGGER_HOME or SWAGGER_CONF not specified
	at com.ig.swagger.search.standalone$find_config_file.invokeStatic(standalone.clj:37)
	at com.ig.swagger.search.standalone$find_config_file.invoke(standalone.clj:36)
	at com.ig.swagger.search.standalone$_main.invokeStatic(standalone.clj:55)
	at com.ig.swagger.search.standalone$_main.doInvoke(standalone.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at com.ig.swagger.search.standalone.main(Unknown Source)
(ENV) ~/Works/zhspecs
```

**docker**

```
w@zhangwei.dev:~ [TESTING]$ sudo docker run -p 7878:3000 -v `pwd`/examples:/config danlebrero/swagger-search
11:49:51,567 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:49:51,567 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:49:51,577 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/swagger-search.jar!/logback.xml]
11:49:51,642 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@41f23499 - URL [jar:file:/app/swagger-search.jar!/logback.xml] is not of type file
11:49:51,914 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:49:51,967 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [jar:file:/app/swagger-search.jar!/logback.xml]
11:49:51,967 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
11:49:51,989 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:49:51,992 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:49:52,066 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:49:52,066 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:49:52,066 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:49:52,067 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:49:52,071 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:49:52,072 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:49:52,073 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@31dbf5bb - Registering current configuration as safe fallback point

2018-08-21 11:49:52 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @15177ms
2018-08-21 11:49:53 [main] INFO  com.ig.swagger.search.standalone - Adding /config to classpath
Exception in thread "main" java.lang.RuntimeException: No swagger.config.edn file at $SWAGGER_HOME or SWAGGER_CONF not specified
	at com.ig.swagger.search.standalone$find_config_file.invokeStatic(standalone.clj:37)
	at com.ig.swagger.search.standalone$find_config_file.invoke(standalone.clj:36)
	at com.ig.swagger.search.standalone$_main.invokeStatic(standalone.clj:55)
	at com.ig.swagger.search.standalone$_main.doInvoke(standalone.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at com.ig.swagger.search.standalone.main(Unknown Source)
```

**Comment by jollychang** [comment]
**change path and docker run**
Should i docker run etcd/consul by myself?
```
w@zhangwei.dev:~/swagger-search [TESTING]$ sudo docker run -p 7878:3000 -v `pwd`/examples:/config danlebrero/swagger-search
11:54:56,474 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:54:56,474 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:54:56,493 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/app/swagger-search.jar!/logback.xml]
11:54:56,660 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@41f23499 - URL [jar:file:/app/swagger-search.jar!/logback.xml] is not of type file
11:54:57,684 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:54:57,748 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [jar:file:/app/swagger-search.jar!/logback.xml]
11:54:57,748 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
11:54:57,778 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:54:57,786 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:54:57,921 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:54:57,921 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:54:57,921 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:54:57,921 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:54:57,922 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:54:57,922 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:54:57,923 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@31dbf5bb - Registering current configuration as safe fallback point

2018-08-21 11:54:58 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @16956ms
2018-08-21 11:54:59 [main] INFO  com.ig.swagger.search.standalone - Adding /config to classpath
2018-08-21 11:54:59 [main] INFO  com.ig.swagger.search.core - Application starting up now ...
Exception in thread "main" java.lang.AssertionError: Assert failed: No discovery providers configured. Please check your configuration
(seq sources)
	at com.ig.swagger.search.discovery$provider.invokeStatic(discovery.clj:31)
	at com.ig.swagger.search.discovery$provider.invoke(discovery.clj:16)
	at com.ig.swagger.search.core$system_start.invokeStatic(core.clj:19)
	at com.ig.swagger.search.core$system_start.invoke(core.clj:13)
	at com.ig.swagger.search.standalone$start.invokeStatic(standalone.clj:13)
	at com.ig.swagger.search.standalone$start.invoke(standalone.clj:12)
	at com.ig.swagger.search.standalone$_main.invokeStatic(standalone.clj:57)
	at com.ig.swagger.search.standalone$_main.doInvoke(standalone.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at com.ig.swagger.search.standalone.main(Unknown Source)
```

**Comment by dlebrero** [comment]
Swagger-search somehow needs to find the list of microservices that you are running. You need to specify in your config file how it is going to do so. See https://github.com/IG-Group/swagger-search#custom-service-discovery

If you just want to play around Swagger-search to see how it looks like, run the local development setup as per https://github.com/IG-Group/swagger-search#development, which runs Swagger-search, etcd and a couple of additional microservices.

**Comment by jollychang** [comment]
Thank you very much!
